version: '3'

# This file uses all local resources.

services:

  redis:
    image: redis:alpine
    ports:
    - 6379:6379
    volumes:
    - ./redis-data:/data

  # includes both the Express api and Vue app
  webapp:
    build:
      context: .
    ports:
    - 8080:8080
    environment:
    - REDIS_URL=redis://redis:6379
    depends_on:
    - redis
